### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by webface** [naver/storybook-addon-preview#2]
I'm trying to add this code view to the example on storybook but i get this error in my tests
```
 FAIL  src/components/TaskList.test.js
  ● Test suite failed to run

    /Applications/MAMP/htdocs/ORGANIMI/taskbox/node_modules/storybook-addon-preview/dist/index.js:5
    import addons, { makeDecorator } from '@storybook/addons';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { withPreview, previewTemplate, DEFAULT_VANILLA_CODESANDBOX } from "storybook-addon-preview";
        | ^
      2 | import React from 'react';
      3 | import { action } from '@storybook/addon-actions';
      4 | 

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/Task.stories.js:1:1)
```
I followed all tthe install instructions tho my implementation may be off.

```
import { withPreview, previewTemplate, DEFAULT_VANILLA_CODESANDBOX } from "storybook-addon-preview";
import React from 'react';
import { action } from '@storybook/addon-actions';

import Task from './Task';
import { withKnobs, text, boolean, number } from "@storybook/addon-knobs";

const opt1 = boolean("opt1", false);
const opt2 = number("num1", 0);
export default {
  component: Task,
  title: 'Task',
  // Our exports that end in "Data" are not stories.
  excludeStories: /.*Data$/,
  decorators:[withKnobs],
  preview: [
    {
        tab: "Vanilla",
        template: previewTemplate`
const inst = new Instance({
opt1: ${"opt1"},
num1: ${"num1"},
});
        `,
        language: "js",
        copy: true,
        codesandbox: DEFAULT_VANILLA_CODESANDBOX(["@egjs/infinitegrid"]),
    },
]
};

export const taskData = {
  id: '1',
  title: 'Test Task',
  state: 'TASK_INBOX',
  updatedAt: new Date(2018, 0, 1, 9, 0),
};

export const actionsData = {
  onPinTask: action('onPinTask'),
  onArchiveTask: action('onArchiveTask'),
};

export const Default = () => <Task task={{ ...taskData }} {...actionsData} />;

export const Pinned = () => <Task task={{ ...taskData, state: 'TASK_PINNED' }} {...actionsData} />;

export const Archived = () => (
  <Task task={{ ...taskData, state: 'TASK_ARCHIVED' }} {...actionsData} />
);
```

**Comment by webface** [comment]
I revised my code
```
import * as React from "react";
import { storiesOf } from "@storybook/react";
import { withKnobs, boolean, number } from "@storybook/addon-knobs";
import {
	withPreview,
	previewTemplate,
	DEFAULT_VANILLA_CODESANDBOX,
} from "storybook-addon-preview";

import Task from "./Task";

const storyName = "Test";
const title = "Test Title";
const stories = storiesOf(storyName, module);
const VirtualComponent = Task;

stories.addDecorator(withKnobs).addDecorator(withPreview);
stories.add(
	title,
	(e) => {
		return (
			<VirtualComponent
				title={title}
				storyName={storyName}
				key={Math.random()}
			/>
		);
	},
	{
		preview: [
			{
				tab: "React",
				template: previewTemplate`
				const inst = new Instance({
					opt1: ${"opt1"},
					num1: ${"num1"},
				});
							`,
				language: "js",
				codesandbox: DEFAULT_VANILLA_CODESANDBOX(["@egjs/infinitegrid"]),
				copy: true,
			},
		],
	}
);
```
Same issue with the import
```
import addons, { makeDecorator } from '@storybook/addons';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import { storiesOf } from "@storybook/react";
      3 | import { withKnobs, boolean, number } from "@storybook/addon-knobs";
    > 4 | import {
        | ^
      5 | 	withPreview,
      6 | 	previewTemplate,
      7 | 	DEFAULT_VANILLA_CODESANDBOX,

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/Test.stories.js:4:1)

Test Suites: 1 failed, 1 passed, 2 total
```

**Comment by daybrush** [comment]
@webface 

Your tester probably don't convert the esm syntax of node_modules. We will add a file in commonjs format.

**Comment by daybrush** [comment]
@webface 

storybook-addon-preview 1.1.2 is released.

Check it again.

**Comment by webface** [comment]
@daybrush I'm using `"storybook-addon-preview": "^1.1.2"` and I get a "Test" component in storybook but when i click it my screen goes blank. This is the code in my story
```
import {
	withPreview,
	previewTemplate,
	DEFAULT_VANILLA_CODESANDBOX,
} from "storybook-addon-preview";
import { storiesOf } from "@storybook/react";
import AppHeader from "./AppHeader.js";
import { withKnobs, text, boolean, number } from "@storybook/addon-knobs";

const storyName = "Test";
const title = "Test Title";
const stories = storiesOf(storyName, module);
const VirtualComponent = AppHeader;

stories.addDecorator(withKnobs).addDecorator(withPreview);
stories.add(
	title,
	(e) => {
		const opt1 = boolean("opt1", false);
		const opt2 = number("num1", 0);
		return (
			<VirtualComponent
				title={title}
				storyName={storyName}
				key={Math.random()}
			/>
		);
	},
	{
		preview: [
			{
				tab: "React",
				template: previewTemplate`
				const inst = new Instance({
					opt1: ${"opt1"},
					num1: ${"num1"},
				});
							`,
				language: "js",
				codesandbox: DEFAULT_VANILLA_CODESANDBOX(["@egjs/infinitegrid"]),
				copy: true,
			},
		],
	}
);
```
Url
```
http://localhost:9009/?path=/story/test--test-title
```

**Comment by daybrush** [comment]
@webface 

DEFAULT_VANILLA_CODESANDBOX needs the Vanilla tab. React should use DEFAULT_REACT_CODESANDBOX.

**Comment by webface** [comment]
@daybrush my component now renders but when I include the `template` object, thee screen stills goes blank. I am using create react app and common js files. Here is updated code, you will notice I commented out parts that don't work and produce white screen

```
import React from "react";
import {
	withPreview,
	previewTemplate,
	DEFAULT_REACT_CODESANDBOX,
} from "storybook-addon-preview";
import { storiesOf } from "@storybook/react";
import AppHeader from "./AppHeader.js";
import { withKnobs, text, boolean, number } from "@storybook/addon-knobs";

const storyName = "Test";
const title = "Test Title";
const stories = storiesOf(storyName, module);
const VirtualComponent = AppHeader;

stories.addDecorator(withKnobs).addDecorator(withPreview);
stories.add(
	title,
	(e) => {
		const opt1 = boolean("opt1", false);
		const opt2 = number("num1", 0);
		return (
			<VirtualComponent
				title={title}
				storyName={storyName}
				key={Math.random()}
			/>
		);
	},
	{
		preview: [
			{
				tab: "React",
				// template: previewTemplate`
				// const inst = new Instance({
				// 	opt1: ${"opt1"},
				// 	num1: ${"num1"},
				// });
				// 			`,
				language: "js",
				codesandbox: DEFAULT_REACT_CODESANDBOX(["@egjs/infinitegrid"]),
				copy: true,
			},
		],
	}
);
```
<img width="784" alt="Screen Shot 2020-06-12 at 8 17 26 AM" src="https://user-images.githubusercontent.com/681890/84502138-c9884400-ac85-11ea-8efc-98f760b683fe.png">

If I uncomment `template` I get a white screen

**Comment by daybrush** [comment]
@webface 
Oh sorry CSS was also required to use codesandbox.

https://github.com/naver/storybook-addon-preview#you-can-use-the-default-codesandbox-presets

I'm going to turn CSS into an option.
